name: LuckyBuildSystem
author: Djreedoo
main: de.djreedoo.luckybuild.main.Main
version: 1.0
api-version: 1.16
#written by DJREEDOO (GERMANY)
commands:
  gm:
    description:
  msg:
    description:
  discord:
    description:
  heal:
    description:
  fliegen:
    description:
  hilfe:
    description:
  hlist:
    description:
  hdelete:
    description:
  commands:
    description:
  pl:
    description:
  plugins:
    description:
  spieler:
    description:
  lootpig:
    description:
  lootcreeper:
    description:
  lootskellet:
    description:
  welt:
    description:
  deleteall:
    description: